"""Bundle agent_core + agent_brain + entry point into one standalone main.py."""
import os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "submission", "main.py")


def strip_local_imports(src):
    src = re.sub(r"^from agent_core import \([^)]*\)\n", "", src, flags=re.M)
    src = re.sub(r"^from agent_core import .*\n", "", src, flags=re.M)
    src = re.sub(r"^from agent_brain import .*\n", "", src, flags=re.M)
    return src


def main():
    core = open(os.path.join(ROOT, "agent_core.py")).read()
    brain = open(os.path.join(ROOT, "agent_brain.py")).read()
    params = {}
    sys.path.insert(0, ROOT)
    from variants import CHAMP
    params = CHAMP
    parts = [
        '"""Kaggriculture agent (generated by build_submission.py - do not edit)."""',
        strip_local_imports(core),
        strip_local_imports(brain),
        "\nPARAMS = %r\n" % (params,),
        """
_BRAIN = Brain(PARAMS)


def agent(obs, config=None):
    try:
        if obs.get("day", 0) == 0 and obs.get("hour", 0) == 0:
            _BRAIN.reset()
        return _BRAIN.act(obs)
    except Exception:
        try:
            import traceback
            traceback.print_exc()
        except Exception:
            pass
        hands = []
        try:
            farms = obs.get("farms") or []
            p = obs.get("player", 0)
            hands = [["PASS"]] * len(farms[p].get("hands") or [])
        except Exception:
            pass
        return {"farmer": ["PASS"], "hands": hands, "market": []}
""",
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    print("wrote", OUT, os.path.getsize(OUT), "bytes")


if __name__ == "__main__":
    main()
