"""Bundle agent_core + agent_brain + entry point into one standalone main.py."""
import os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
VARIANT = os.environ.get("VARIANT")            # build a named variant instead of the champion
# Kaggle requires the entry file to be named main.py, so each build gets its own dir.
OUT = (os.path.join(ROOT, "submission", VARIANT, "main.py") if VARIANT
       else os.path.join(ROOT, "submission", "main.py"))


def strip_local_imports(src):
    src = re.sub(r"^from agent_core import \([^)]*\)\n", "", src, flags=re.M)
    src = re.sub(r"^from agent_core import .*\n", "", src, flags=re.M)
    src = re.sub(r"^from agent_brain import .*\n", "", src, flags=re.M)
    src = re.sub(r"^from agent_animal import .*\n", "", src, flags=re.M)
    src = re.sub(r"^\s+expected_units, harvest_day, watering_days, water_window, clear_caches,\n\)\n", "", src, flags=re.M)
    return src


def main():
    core = open(os.path.join(ROOT, "agent_core.py")).read()
    brain = open(os.path.join(ROOT, "agent_brain.py")).read()
    animal = (strip_local_imports(open(os.path.join(ROOT, "agent_animal.py")).read())
              if VARIANT == "animal" else "")
    params = {}
    sys.path.insert(0, ROOT)
    if VARIANT == "animal":
        params = {}
        print("building variant: animal (AnimalBrain)")
    elif VARIANT:
        from variants import VARIANTS
        params = VARIANTS[VARIANT]
        print("building variant:", VARIANT)
    else:
        from variants import CHAMP
        params = CHAMP
    parts = [
        '"""Kaggriculture agent (generated by build_submission.py - do not edit)."""',
        strip_local_imports(core),
        strip_local_imports(brain),
        animal,
        "\nPARAMS = %r\n" % (params,),
        """
# One planner per seat: Kaggle's validation episode plays this agent against a
# copy of itself, which may share module state between both players.
_BRAINS = {}
_CLS = AnimalBrain if "AnimalBrain" in dir() else Brain


def agent(obs, config=None):
    try:
        p = obs.get("player", 0)
        b = _BRAINS.get(p)
        if b is None or (obs.get("day", 0) == 0 and obs.get("hour", 0) == 0):
            b = _CLS(PARAMS)
            _BRAINS[p] = b
        return b.act(obs, config)
    except Exception:
        try:
            import traceback
            traceback.print_exc()
        except Exception:
            pass
        hands = []
        try:
            farms = obs.get("farms") or []
            p = obs.get("player", 0)
            hands = [["PASS"]] * len(farms[p].get("hands") or [])
        except Exception:
            pass
        return {"farmer": ["PASS"], "hands": hands, "market": []}
""",
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    print("wrote", OUT, os.path.getsize(OUT), "bytes")
    _selftest()


def _selftest():
    """Run a full episode through the bundle and fail loudly on any error."""
    import importlib.util, io, contextlib
    spec = importlib.util.spec_from_file_location("kaggri_sub_test", OUT)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    from kaggle_environments import make
    buf = io.StringIO()
    env = make("kaggriculture", configuration={"episodeSteps": 720, "seed": 11},
               debug=True)
    with contextlib.redirect_stderr(buf), contextlib.redirect_stdout(buf):
        env.run([m.agent, "starter"])
    out = buf.getvalue()
    if "Traceback" in out or "Error" in out:
        raise SystemExit("SELFTEST FAILED:\n" + out[:2000])
    rewards = [float(s["reward"] or 0) for s in env.steps[-1]]
    status = [s["status"] for s in env.steps[-1]]
    if status[0] != "DONE" or rewards[0] < 20000:
        raise SystemExit("SELFTEST FAILED: rewards=%s status=%s" % (rewards, status))
    print("selftest OK: reward=${:,.0f}".format(rewards[0]))


if __name__ == "__main__":
    main()
